#define TINYGLTF_IMPLEMENTATION
#include <tinygltf/tiny_gltf.h>
#define STB_IMAGE_IMPLEMENTATION
#include <stb_image.h>
#define STB_IMAGE_WRITE_IMPLEMENTATION
#include <stb_image_write.h>
#define DOCTEST_CONFIG_IMPLEMENT
#include <doctest/doctest.h>
#define MINIAUDIO_IMPLEMENTATION
#include <miniaudio.h>